### ISSUE TITLE
Error while trying to write on a PDF v.1.6

### ISSUE THREAD

**Issue by frithnanth** [p6-pdf/PDF-API6#3]
I'm using this program:

```
use PDF::API6;

my PDF::API6 $pdf .= open('old.pdf');
my $page = $pdf.page(1);
my $font = $pdf.core-font('Helvetica-Bold');
$page.text: {
  .font = $font, 20;
  .text-position = 200, 700;
  .say('Hello World!');
}
$pdf.save-as('new.pdf');
```
to open an existing PDF file, write a string on it, and save the result.
While it works on a PDF v.1.3, it doesn't on a PDF v.1.6.
The error I get is:

```
Type check failed in assignment to @ops; expected Pair but got Str ("tba: ignored-block =...)
  in method render at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 71
  in method gfx at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 45
  in method text at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 50
  in block <unit> at ./test.p6 line 8
```

**Comment by dwarring** [comment]
Hi @frithnanth 
The particular issue is that that PDF includes some extended content in a BX .. EX block, which hasn't been implemented.

If you are able, it would help to attach an example PDF, to this ticket, give me a real-world example.

**Comment by frithnanth** [comment]
I bursted the original PDF, so I can attach single pages, with different errors:

[pdf1.pdf](https://github.com/p6-pdf/PDF-API6/files/1865339/pdf1.pdf)
Type check failed in assignment to @ops; expected Pair but got Str ("tba: ignored-block =...)
  in method render at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 71
  in method gfx at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 45
  in method text at /home/nando/.perl6/sources/77CED8D94355E86EA0C383F654D5B2B924829E89 (PDF::Content::Graphics) line 50
  in block <unit> at ./p.p6 line 8

[pdf2.pdf](https://github.com/p6-pdf/PDF-API6/files/1865340/pdf2.pdf)
unexpected 're' (Rectangle) operation, in Path context, following 're' (Rectangle)
  in block  at /home/nando/.perl6/sources/F15757B1C156D479F3BFD4784BF16DC8401F6336 (PDF::Content::Ops) line 353

[pdf3.pdf](https://github.com/p6-pdf/PDF-API6/files/1865341/pdf3.pdf)
unexpected 'm' (MoveTo) operation, in Path context, following 're' (Rectangle)
  in block  at /home/nando/.perl6/sources/F15757B1C156D479F3BFD4784BF16DC8401F6336 (PDF::Content::Ops) line 353

Thank you!

**Comment by dwarring** [comment]
Fixed the page-1 error in  PDF::Grammar 0.1.5. At least finishes and produces and updated PDF.

Looking at the warnings.

**Comment by dwarring** [comment]
Fixed the remaining warnings in PDF::Content, which no longer attempts to render the page.

Now works faster and without displaying any warnings.

Please install and reinstall PDF::Grammar PDF and PDF::Content, before retrying.

**Comment by frithnanth** [comment]
Hi @dwarring ,
Now everything is way faster!
I still get an error processing pdf2.pdf:
```
indirect reference without associated reader: 8 0 R
  in method deref at /home/nando/.perl6/sources/2972298450774005539A9FBDF0584F328B3CC7D8 (PDF::COS::Tie) line 217
  in method AT-KEY at /home/nando/.perl6/sources/315E33EF8D0BDC27C34F29BA8897129D1AF81F6A (PDF::COS::Tie::Hash) line 50
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 29
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 29
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method body at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 67
  in method ast at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 259
  in method ast at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 127
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 149
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 144
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 130
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in block <unit> at ./test.p6 line 13
```
No error processing pdf1.pdf and pdf3.pdf.

**Comment by frithnanth** [comment]
Hi @dwarring ,
Now everything is way faster!
I still get an error processing pdf2.pdf:
```
indirect reference without associated reader: 8 0 R
  in method deref at /home/nando/.perl6/sources/2972298450774005539A9FBDF0584F328B3CC7D8 (PDF::COS::Tie) line 217
  in method AT-KEY at /home/nando/.perl6/sources/315E33EF8D0BDC27C34F29BA8897129D1AF81F6A (PDF::COS::Tie::Hash) line 50
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 29
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 29
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method ref-count at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 22
  in method body at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 67
  in method ast at /home/nando/.perl6/sources/10B2BD23594B63F77C35AD268A1C14D3780372F4 (PDF::IO::Serializer) line 259
  in method ast at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 127
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 149
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 144
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in method save-as at /home/nando/.perl6/sources/AFC1DE710F913E1687C329ABF85F4F23CC2EA1C3 (PDF) line 130
  in method save-as at /home/nando/.perl6/sources/7184DFE52FD9F8ECA061E28AF380099BACB39C9A (PDF::Class) line 61
  in block <unit> at ./test.p6 line 13
```
No error processing pdf1.pdf and pdf3.pdf.

**Comment by frithnanth** [comment]
When I first uninstalled & reinstalled the modules, I got PDF::Class:ver<0.1.3>, one hour later I saw that there was a PDF::Class:ver<0.1.7> available, so I upgraded.
Now pdf2.pdf works fine too.
If you don't mind, I will test your software on more PDF files.
Thank you!

**Comment by dwarring** [comment]
Thanks for your feedback.
